# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "/den/face0xff"
tab:              "face0xff's den"
tagline:          'My personal blog'
description:      'My personal blog'
url:              https://face.0xff.re/
baseurl:          "/"
baseimg:          "/public/images"

author:
  name:           'face0xff'
  url:            https://github.com/face0xff

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/face0xff/face0xff.github.io

ctf:              https://ctf.0xff.re/
shrecs:           https://shrecs.fr/
