# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            "/den/face0xff"
tab:              "face0xff's den"
tagline:          'My personal blog'
description:      'My personal blog. <a href="https://github.com/face0xff" target="_blank">@face0xff</a>'
url:              https://blog.feisu.win/
baseurl:          /

author:
  name:           'face0xff'
  url:            https://github.com/face0xff

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/face0xff/face0xff.github.io
